name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create build directory
      run: mkdir -p tests/build
        
    - name: Run CMake
      working-directory: ${{github.workspace}}/tests/build
      run: cmake ../.
        
    - name: Build
      working-directory: ${{github.workspace}}/tests/build
      run: make
        
    - name: Run tests
      working-directory: ${{github.workspace}}/tests/build
      run: ./tests
