name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        which cmake
        cmake --version
        mkdir -p tests/build
        
    - name: Run CMake
      working-directory: ${{github.workspace}}/tests/build
      run: |
        cmake ../.
        
    - name: Make
      working-directory: ${{github.workspace}}/tests/build
      run: |
        make
        
    - name: Test
      working-directory: ${{github.workspace}}/tests/build
      run: ./tests

    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      
